version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - my-network
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    networks:
      - my-network
networks:
  my-network:
